import ProjectDescription

// ===============================================
// 🚨 This file is auto-generated.
// Do NOT edit this file manually.
//
// Generated by: `tuist scaffold feature --name RootTab`
// Location: Tuist/Templates/feature/feature.swift
//
// Purpose:
// - Register Feature identifier safely
// - Use as: Feature.rootTab
// ===============================================

public extension Feature {
  /// Example: Feature.rootTab / Feature.home / Feature.calendar ...
  static let rootTab = Feature("RootTab")
}