import ProjectDescription

// ===============================================
// 🚨 This file is auto-generated.
// Do NOT edit this file manually.
//
// Generated by: `tuist scaffold feature --name Schedule`
// Location: Tuist/Templates/feature/feature.swift
//
// Purpose:
// - Register Feature identifier safely
// - Use as: Feature.schedule
// ===============================================

public extension Feature {
  /// Example: Feature.rootTab / Feature.home / Feature.calendar ...
  static let schedule = Feature("Schedule")
}